language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
- pip install coveralls requests requests_mock
script: coverage run --source viper-metascan/metascan/ -m py.test tests -v
after_success:
  coveralls
